# Generated by Django 2.2.1 on 2019-12-11 21:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_bonus', models.PositiveIntegerField(default=4)),
                ('steal_bonus', models.PositiveIntegerField(default=6)),
                ('attack_bonus', models.PositiveIntegerField(default=6)),
                ('heal_bonus', models.PositiveIntegerField(default=7)),
                ('cover_bonus', models.PositiveIntegerField(default=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_roster.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('victory_points', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_roster.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0)),
                ('destination_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='char_roster.Location')),
                ('origin_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_roster.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('work_power', models.PositiveIntegerField(default=9)),
                ('steal_power', models.PositiveIntegerField(default=9)),
                ('attack_power', models.PositiveIntegerField(default=9)),
                ('max_hp', models.PositiveIntegerField(default=35)),
                ('curr_hp', models.PositiveIntegerField(default=models.PositiveIntegerField(default=35), validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(default=35))])),
                ('fame', models.PositiveIntegerField(default=0)),
                ('money', models.PositiveIntegerField(default=0)),
                ('curr_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_roster.Location')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_roster.Team')),
            ],
        ),
    ]
