# Generated by Django 2.2.1 on 2019-12-11 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='curr_hp',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=40), validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(default=40))]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_hp',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='agent',
            name='work_power',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='attack_bonus',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='cover_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='heal_bonus',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='steal_bonus',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='work_bonus',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
