# Generated by Django 2.2.1 on 2019-12-12 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0002_auto_20191212_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='famous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='attack_power',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='agent',
            name='curr_hp',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=32), validators=[django.core.validators.MaxValueValidator(models.PositiveIntegerField(default=32))]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_hp',
            field=models.PositiveIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='agent',
            name='steal_power',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='agent',
            name='work_power',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='attack_bonus',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='location',
            name='heal_bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='steal_bonus',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='location',
            name='work_bonus',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
