# Generated by Django 2.2.1 on 2019-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0004_auto_20191213_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='curr_hp',
            field=models.IntegerField(default=models.IntegerField(default=32)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_hp',
            field=models.IntegerField(default=32),
        ),
    ]
