# Generated by Django 2.2.1 on 2019-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0005_auto_20191213_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='attack_stat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='heal_stat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='steal_stat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='work_stat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='curr_hp',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_hp',
            field=models.IntegerField(default=35),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
