# Generated by Django 2.2.1 on 2019-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0006_auto_20191213_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cover_stat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='spended_money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
