# Generated by Django 2.2.1 on 2019-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char_roster', '0007_auto_20191214_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='attack_power_origin',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='agent',
            name='steal_power_origin',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='agent',
            name='work_power_origin',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
